### ISSUE TITLE
Installing Feature Flags fails on x64 machines.

### ISSUE THREAD

**Issue by v-wenkecheng** [pharring/FeatureFlags#17]
**Azure DevOps work item**:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1845492

**Version used:**
1. Install VS 17.7 Preview 3: [d17.7-33903.240](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=8016064&view=results)

**Platform**
- [x] Windows
- [ ] Linux
- [ ] Mac

**Repro Steps**

1. Install the extension using the link below:

   [Install Feature Flags](https://marketplace.visualstudio.com/items?itemName=PaulHarrington.FeatureFlagsPreview)

**Note:**
This issue does not repro on Dev17.6.4 and Dev 17.7 Preview 2.
This issue repro on main branch and rel/d branch.

**Actual Result**
Installing Feature Flags fails on x64 machines.
![image](https://github.com/pharring/FeatureFlags/assets/69494255/1270360d-ba8e-4378-9cfd-66c88fb5d72c)

**Install Log**

7/4/2023 2:10:56 AM - Microsoft VSIX Installer
7/4/2023 2:10:56 AM - -------------------------------------------
7/4/2023 2:10:56 AM - vsixinstaller.exe version:
7/4/2023 2:10:56 AM - 17.7.2161+2fedbb2efb
7/4/2023 2:10:56 AM - -------------------------------------------
7/4/2023 2:10:56 AM - Command line parameters:
7/4/2023 2:10:56 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\v-elenafeng\Downloads\FeatureFlags.vsix
7/4/2023 2:10:56 AM - -------------------------------------------
7/4/2023 2:10:56 AM - Microsoft VSIX Installer
7/4/2023 2:10:56 AM - -------------------------------------------
7/4/2023 2:10:56 AM - Initializing Install...
7/4/2023 2:10:56 AM - Searching for applicable products...
7/4/2023 2:10:56 AM - System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.VisualStudio.Threading, Version=17.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VSIXInstaller.ExtensionEngineFactoryForSku.LoadEngineAssembly(SupportedVSSKU sku)
   at VSIXInstaller.ExtensionEngineFactoryForSku.GetEngineAssembly(SupportedVSSKU sku) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\ExtensionEngineFactoryForSku.cs:line 110
   at VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\ExtensionEngineFactoryForSku.cs:line 89
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 138
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 28
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 101
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 42
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 267
   at VSIXInstaller.App.Initialize() in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 225
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

 WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Expected Result**
The Feature Flags can be installed successfully.

**Comment by pharring** [comment]
Not repro. If you can still repro this with the latest VS 2022 version (1.0.10), please re-open.
